### PR TITLE
scroll to previous/next selected

### PR DESCRIPTION
**Pull request by gillins**
Has it happened to you where you've done a geographic select or a select by expression and it scrolls to the first row but then you struggle to find any of the other rows that are selected? This is becoming more of a problem with bigger RATS...

So I've added a fast forward and rewind icon to the top and bottom of the scroll bar to scroll to the next or previous selected row. @neilflood @petescarth can you guys give this a quick test and let me know if this is ok?

### CODE REVIEW

**Comment by neilflood** [comment]
Yes, just tried it, and it seems to work. I do agree that for large-ish RATs, scrolling through the table looking for something is essentially unusable, so it is certainly good to try to address it. 

- The tooltip text on those buttons seems strangely worded.
- I could not quite work out how it decided the amount to scroll by, but it seemed to be usable, so fine.
- Would this be better done by just giving a "Display only selected rows" toggle? I am unsure either way, I was just wondering. 

Well done, though.

**Comment by gillins** [comment]
Thanks for checking. 

re: tooltips. Open to suggestions, was trying to avoid the words "previous selected" as this might mean the last set of rows selected rather than "towards the top of the RAT". What do you think the best wording would be.

re: amount to scroll. It tries to move the newly found row to the middle of the current page. Not sure I have this right though...

re: "Display only selected rows". Yes, maybe. But would be more work...

**Comment by neilflood** [comment]
re: tooltips. Yes, I get what you are saying about words like "next" and "previous". However, I think the problem is that you accidentally included the word "to" twice. Should this be "Scroll up to selected" ? That would make better sense.

**Comment by gillins** [comment]
Ah yes you are right! Try that.

**Comment by neilflood** [comment]
Much better :-)

**Comment by gillins** [comment]
If you think this is an acceptable solution for now, I'll merge this. Doing the "Display only selected rows" is Quite Hard (will discuss details with @neilflood). We'd want to be certain it's the way to go before embarking....

**Comment by neilflood** [comment]
I am certainly happy with this idea. I don't have strong feelings about the other approach, I was just thinking aloud.

**Pull request merged**
